[package]
name = "sonus-auris-ores-middleware-auth-security-certification"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ores-middleware = { git = "https://github.com/ORESoftware/ores-middleware", rev = "f3ee887885c63f8cfd5ad7190629dd8852f957a8", default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
