[package]
name = "sonus-auris-ores-middleware-auth-security-certification"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ores-middleware = { git = "https://github.com/ORESoftware/ores-middleware", rev = "00ec8e427cee04df65887ecaa630ff35a7ccc3b2", default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
